### ISSUE TITLE
latest release on crates.io is 0.8 but not reflected in repo

### ISSUE THREAD

**Issue by TDHolmes** [djmcgill/form#15]
I think you bumped the version locally and published, but forgot to push?

**Comment by TDHolmes** [comment]
[See Cargo.toml](https://github.com/djmcgill/form/blob/fcb397a39d633ba7fbda057483e0587cef05f25d/Cargo.toml#L3)

**Comment by djmcgill** [comment]
That's exactly what happened, fixed now.
