### ISSUE TITLE
`env_logger 0.9.x` uses `atty` that has CVE and is unmaintained

### ISSUE THREAD

**Issue by michalfita** [djmcgill/form#21]
Details: https://github.com/advisories/GHSA-g98v-hv3f-hcfr

Looks like `env_logger` 0.10.0 changed `atty` to `is-terminal`.

This issue triggers Dependabot security warnings.

**Comment by djmcgill** [comment]
Thanks, fixed and released as 0.11.1.

**Comment by michalfita** [comment]
Thanks for quick response.
