### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jacobrosenthal** [djmcgill/form#7]
#6 is working great and were hoping to release a crate based on this.

Any chance of a point release?

Thanks!

**Comment by djmcgill** [comment]
Done! https://crates.io/crates/form/0.5.0
Apologies for the delay. I finally got around to adding at least a cursory integration test on CI so releases aren't stalled by me getting around to manual testing.

I bumped it to 0.5.0 just so people can find the version easier than pinning scripts to a minor version.
